### ISSUE TITLE
Loading notebook

### ISSUE THREAD

**Issue by msseibel** [thallesilva/blog-resources#1]
Hey sthalles,
im receiving the following error when trying to load the notebooks "semi-supervised_learning.ipynb" or "DCGAN.ipynb":
Unreadable Notebook: C:\path_to_notebook\semi-supervised_learning.ipynb UnicodeDecodeError('utf8', ....
The "LinearModel.ipynb" example works. 

what settings do I have to change or give me a hint how to fix it?

**Comment by sthalles** [comment]
Hello,
Based on the error, I would but it is a problem from your side. I just tested the notebooks and they seem fine. It says it is a problem of encoding. Try to run 'python3 -m ipykernel install' and make sure your are using python 3.

**Comment by ussaema** [comment]
I have the same error, the file seems to be defect. It is even not readable on github!

**Comment by msseibel** [comment]
Sorry, I forgot to update.  I copied the notebook on windows with cntrl+c. Check that the semicolons ' ' are proper copied and not converted to something like  ´ .
